language: node_js
node_js:
  - 8
cache: yarn

# Define global C++ compiler version
env:
  global:
    - CXX=g++-4.8
before_install:
  # Yarn defaults to an old version, make sure we
  # get an up to date version
  - npm install -g yarn@1.10.1
  - '[ "${NPM_TOKEN+x}" ] && echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc || echo "Skipping .npmrc creation";'

before_script:
  - cp config/ci.config.json config/project.json
  - firebase setup:emulators:firestore
  - firebase serve --only firestore &

# Misc Addons/Configs
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

matrix:
  fast_finish: true

jobs:
  include:
    - name: batch_writes.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/batch_writes.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: cursor.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/cursor.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: database.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/database.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: fields.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/fields.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: server_timestamp.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/server_timestamp.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: transactions.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/transactions.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: type.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/type.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: validation.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/api/validation.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
    - name: remote.test.ts
      stage: test
      script:
        - sleep 5
        - cd packages/firestore
        - npx mocha 'test/integration/remote/remote.test.ts' --require ts-node/register/type-check --require index.node.ts --timeout 5000 --exit
      env: FIRESTORE_EMULATOR_PORT=8080
